

package Jt;

/**
  * Represents remote Jt Exceptions: exceptions generated by remote objects.
  */

public class JtRemoteException extends JtException {

   private String trace;

   public JtRemoteException () {}


 /**
   * Specifies the remote stack trace
   */
   public void setTrace (String trace) {
     this.trace = trace;
   }

 /**
   * Returns the remote stack trace. 
   */

   public String getTrace () {
     return (trace);
   }

   public JtRemoteException (String s) {
	super (s);
   }

}
